# Generated by Django 5.2.4 on 2026-05-30 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_key', models.SlugField(help_text="Internal category key, e.g. 'gpu', 'cpu', 'prebuilt'", primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full product name shown on the storefront', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly identifier, e.g. nemesis-rtx-5090-edition', max_length=200, unique=True)),
                ('description', models.TextField(help_text='Full product description shown on detail page')),
                ('price', models.DecimalField(decimal_places=2, help_text='Current selling price in USD', max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original price (leave blank if no discount)', max_digits=10, null=True)),
                ('image', models.CharField(blank=True, help_text="Static image filename without extension, e.g. 'nemesis_rtx_5090_edition'", max_length=100)),
                ('image_upload', models.ImageField(blank=True, help_text='Upload a product image (overrides the static image name above)', null=True, upload_to='products/')),
                ('badge', models.CharField(blank=True, help_text="Short badge label shown on the card, e.g. 'FLAGSHIP', 'NEW', 'HOT'", max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, help_text='Average rating out of 5.0', max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Current units in stock')),
                ('in_stock', models.BooleanField(default=True, help_text='Toggle product availability')),
                ('cpu', models.CharField(blank=True, help_text='Processor / CPU spec line', max_length=200)),
                ('gpu', models.CharField(blank=True, help_text='Graphics card / GPU spec line', max_length=200)),
                ('ram', models.CharField(blank=True, help_text='Memory / RAM spec line', max_length=200)),
                ('storage', models.CharField(blank=True, help_text='Storage spec line', max_length=200)),
                ('mobo', models.CharField(blank=True, help_text='Motherboard spec line', max_length=200)),
                ('psu', models.CharField(blank=True, help_text='Power supply spec line', max_length=200)),
                ('cooler', models.CharField(blank=True, help_text='Cooler spec line', max_length=200)),
                ('case', models.CharField(blank=True, help_text='Case spec line', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in homepage featured section')),
                ('is_trending', models.BooleanField(default=False, help_text='Show in homepage trending section')),
                ('category', models.ForeignKey(help_text='Select the product category', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='shop.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
