# Generated by Django 5.2.4 on 2026-06-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_feedback_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='category',
            field=models.CharField(choices=[('performance', 'Performance'), ('build', 'Build Quality'), ('value', 'Value for Money'), ('shipping', 'Shipping & Packaging'), ('support', 'Customer Support'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='review',
            name='source',
            field=models.CharField(choices=[('storefront', 'Storefront'), ('admin', 'Admin Portal')], default='storefront', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
